### ISSUE TITLE
A few issues I've run into.

### ISSUE THREAD

**Issue by HaMeRoNy** [shdwcat/YUI#21]
Can i fix this somehow?
If I try to close this window "buttons", the program crashes, no reaction to other windows if i click to close it.
![изображение](https://user-images.githubusercontent.com/65815547/185517578-48d29c28-40bd-4292-b9a4-382dbbc5131a.png)
![изображение](https://user-images.githubusercontent.com/65815547/185520090-85626efd-1ba4-4672-b135-f747887ea8cb.png)

Here's another one, if I scroll the slider past the center, I can't interact with it anymore until I scroll to the top of the page myself.
![изображение](https://user-images.githubusercontent.com/65815547/185518065-4779e9cd-0036-4525-95f5-b113e749bfa3.png)
If you go into the inventory, put on any thing on hero, click on the back, enter the inventory again, then there is a very high chance that there is nothing more to work. But if I go back again and sing the therme, everything will be fixed.

**Comment by shdwcat** [comment]
Hi, thanks for these reports!
* the overlap issue is known and I'll fix it at some point
* the error when closing a window is fixed in Dev if you want to try that (you'll need to clone the project locally, not download it)
The other issues with the viewport and the inventory are new to me, I'll investigate them when I can!

Thanks again

**Comment by HaMeRoNy** [comment]
I want to say that you did a very cool job! The functionality is amazing.
Do not quit the project, it has great prospects)
If suddenly I stumble upon any other malfunctions, I will definitely notify you about it! Thank you!

**Comment by shdwcat** [comment]
Finally got back to working on this thing. I believe all of these issues should now be fixed in the dev branch as of 80aaf0b
