### ISSUE TITLE
failed to run the example YUI

### ISSUE THREAD

**Issue by digimonlopmon** [shdwcat/YUI#29]
After downloading the zip file and setting the YUIExampleRoom1 to the default room and run it, there was an error:

ERROR in
action number 1 
of Create Event
for object yui_document:

Unable to find a handler for exception Unable to find theme with name: default

at gml_Script_yui_resolve_theme(line 7)-                                     throw
yui+error("Unable to find theme with name: " + theme_name);

**Comment by shdwcat** [comment]
The download code button doesn't work (for stupid GitHub reasons). You can either use the YYMPS package or clone the repo until I fix that (near future). Thanks for checking it out!

**Comment by shdwcat** [comment]
Fixed in 559d4c7
