### ISSUE TITLE
Circular layout (like a item wheel)

### ISSUE THREAD

**Issue by zice-o-lantern** [shdwcat/YUI#5]
Hello shwdcat, I'd like to make a weapon wheel for my game like in Zelda: Twilight Princess or GTA V. For this, a new circular component for layout would be handy! 

Sincerely, Zice
![inv](https://user-images.githubusercontent.com/54986379/153783318-a124994f-6245-4b3b-b7a2-9af3a7bcedd3.jpg)
![WeaponWheel-GTAV-next](https://user-images.githubusercontent.com/54986379/153783322-0a2631ce-cfe3-4f0a-b60e-9cf63928fe93.jpg)

**Comment by shdwcat** [comment]
https://github.com/shdwcat/YUI/commit/7ea0b57bc1f39f5de6f02b63f0b67bec101b140a

Radial Layout is added in the above commit. You can see it in the Layout Examples screen, and check the .yui file for comments about how to use it.

Let me know if anything is lacking!
