### ISSUE TITLE
Slider bar isn't clamped

### ISSUE THREAD

**Issue by zice-o-lantern** [shdwcat/YUI#7]
Hello shwdcat, I was testing your slider and I lost the slider cursor, and now I can't find it anymore 😢 
Please retrieve my slide cursor.

Sincerely, Zice

https://user-images.githubusercontent.com/54986379/154037613-bd2cd65f-1db8-4631-aacc-0411bedb12c7.mp4

**Comment by shdwcat** [comment]
Fixed in https://github.com/shdwcat/YUI/commit/19825968c4d53b41d10c989d120fcc2c7fce200b
